secret_key_base: XXXXXXXXXXXXXXXXXXX
port: 3000
name: authy-example

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:@localhost:5432/authy_example_development
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  AUTHY_API_KEY: XXXXXXXXXX
  TWILIO_ACCOUNT_SID: YYYYYYYYYY
  TWILIO_AUTH_TOKEN: ZZZZZZZZZZZZZZZZ
